---
- name: Delete DNS records
  when: >-
    external_access_base_domain in external_access_supported_base_domains | default([])
  ansible.builtin.include_role:
    name: "{{ dns_class }}"
    tasks_from: delete
  vars:
    dns_zone: "{{ lookup('env', 'DNS_ZONE') | default(external_access_base_domain, true) }}"
    dns_record_name: "{{ item }}"
    dns_record_type: A
  loop:
    - "api.{{ external_access_name }}.{{ external_access_base_domain }}"
    - "api-int.{{ external_access_name }}.{{ external_access_base_domain }}"
    - "*.apps.{{ external_access_name }}.{{ external_access_base_domain }}"
