title: OpenShift Small Cluster
description: >
  Builds a minimally configured OpenShift cluster with a configurable OCP
  version. Default version: 4.22.0.

default_node_request:
- resourceClass: fc430
  numberOfNodes: 2

allowed_resource_classes: []
