---
- name: Create an ExternalIPPool resource
  hosts: localhost
  gather_facts: false

  vars:
    external_ip_pool: "{{ ansible_eda.event.payload }}"
    external_ip_pool_name: "{{ ansible_eda.event.payload.metadata.name }}"
    implementation_strategy: "{{ ansible_eda.event.payload.spec.implementationStrategy }}"
    template_parameters: {}

  pre_tasks:
    - name: Show EDA Event
      ansible.builtin.debug:
        var: ansible_eda.event.payload

  tasks:
    - name: Display ExternalIPPool information
      ansible.builtin.debug:
        msg:
          - "ExternalIPPool name: {{ external_ip_pool_name }}"
          - "Implementation strategy: {{ implementation_strategy }}"
          - "Template parameters: {{ template_parameters }}"

    - name: Call the selected ExternalIPPool role
      ansible.builtin.include_role:
        name: "{{ template_id_override | default('osac.templates.' + (implementation_strategy | replace('-', '_'))) }}"
        tasks_from: create_external_ip_pool
