{{- if .Values.configAsCode.eeImage }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.configAsCode.secret }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "osac-aap.labels" . | nindent 4 }}
stringData:
  AAP_EE_IMAGE: {{ .Values.configAsCode.eeImage | quote }}
  AAP_PROJECT_GIT_URI: {{ .Values.configAsCode.projectGitUri | quote }}
  AAP_PROJECT_GIT_BRANCH: {{ .Values.configAsCode.projectGitBranch | quote }}
{{- end }}
