---
- name: Allocate VLAN ID from pool
  hosts: net_nodes[0]
  gather_facts: false
  tasks:
    - name: Allocate VLAN
      ansible.builtin.include_role:
        name: agentless_net.ipam.vlan_id
        tasks_from: allocate
