---
- name: Delete VLAN from switches
  hosts: switches
  gather_facts: false
  tasks:
    - name: Delete VLAN
      ansible.builtin.include_role:
        name: agentless_net.l2.vlan
        tasks_from: delete
