---
- name: Create L3 router namespace
  hosts: net_nodes
  gather_facts: false
  tasks:
    - name: Create router
      ansible.builtin.include_role:
        name: agentless_net.l3.router
        tasks_from: create
