---
- name: Create OpenStack network for BareMetalPool
  ansible.builtin.include_role:
    name: osac.esi.network
  vars:
    network_state: present
    network_suffix: "{{ bare_metal_pool.metadata.name }}"
